# Supervised neural nets

In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
%matplotlib inline

artworks = pd.read_csv('https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv')
artworks.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ThumbnailURL',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='object')

In [2]:
# Select Columns.
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

In [3]:
artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year

# Remove multiple nationalities, genders, and artists.
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    '([0-9]{4})', expand=False))[:-1]

# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat with other variables, but artists slows this wayyyyy down so we'll keep it out for now
X = pd.get_dummies(X, sparse=True)
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

X.head()

URL  ThumbnailURL  Height (cm)  Width (cm)  YearAcquired  Gender_()  \
0  True          True      48.6000    168.9000          1996          0   
1  True          True      40.6401     29.8451          1995          0   
2  True          True      34.3000     31.8000          1997          0   
3  True          True      50.8000     50.8000          1995          0   
4  True          True      38.4000     19.1000          1997          0   

   Gender_(Female)  Gender_(Male)  Gender_(male)  Gender_\(multiple_persons\)  \
0                0              1              0                            0   
1                0              1              0                            0   
2                0              1              0                            0   
3                0              1              0                            0   
4                0              1              0                            0   

   ...   2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  
0  ...      0     0     0     0     0     0     0     0     0     0  
1  ...      0     0     0     0     0     0     0     0     0     0  
2  ...      0     0     0     0     0     0     0     0     0     0  
3  ...      0     0     0     0     0     0     0     0     0     0  
4  ...      0     0     0     0     0     0     0     0     0     0  

[5 rows x 314 columns]

In [4]:
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [5]:
mlp.score(X, Y)

0.6880334171927659

In [6]:
Y.value_counts()/len(Y)

Prints & Illustrated Books    0.523140
Photography                   0.228737
Architecture & Design         0.111131
Drawings                      0.103081
Painting & Sculpture          0.033911
Name: Department, dtype: float64

In [7]:
cross_val_score(mlp, X, Y, cv=5)

array([0.53471926, 0.57447313, 0.54777614, 0.59660116, 0.47220508])

We included one parameter: hidden layer size. How many layers to include is determined by two things: computational resources and cross validation searching for convergence. It's generally < # of input variables.

You can also set an alpha. Neural networks like this use a regularization parameter that penalizes large coefficients – alpha scales that penalty.

Lastly, the activation function determines whether the output from an individual perceptron is binary or continuous. By default, this is a 'relu' ('rectified linear unit function') function. Sigmoid (called 'logistic' by SKLearn, because it's a 'logistic sigmoid function') is a reasonable alternative. The sigmoid allows for continuous variables between 0 and 1, which results in a more nuanced model. It does come at the cost of increased computational complexity.

## Drill: Playing with layers

Experiment with different hidden layer structures. You can try this on a subset of the data to improve runtime. See how things vary. See what seems to matter the most. Feel free to manipulate other parameters as well. It may also be beneficial to do some real feature selection work.

In [8]:
X = X[:math.floor(X.shape[0]/2)]
Y = Y[:math.floor(Y.shape[0]/2)]

print(X.shape, Y.shape)

(52667, 314) (52667,)


In [9]:
mlp_2_lyrs = MLPClassifier(hidden_layer_sizes=(1000,1000))
mlp_2_lyrs.fit(X, Y)
cross_val_score(mlp_2_lyrs, X, Y, cv=5)

array([0.63046986, 0.6957471 , 0.77954999, 0.79530998, 0.44065705])

In [10]:
# alpha : float, optional, default 0.0001
mlp_lower_alpha = MLPClassifier(hidden_layer_sizes=(1000,), alpha=0.00001)
mlp_lower_alpha.fit(X, Y)
cross_val_score(mlp_lower_alpha, X, Y, cv=5)

array([0.37095396, 0.61828365, 0.71812399, 0.78657552, 0.44331561])

In [11]:
mlp_higher_alpha = MLPClassifier(hidden_layer_sizes=(1000,), alpha=0.001)
mlp_higher_alpha.fit(X, Y)
cross_val_score(mlp_higher_alpha, X, Y, cv=5)

array([0.61737067, 0.39196886, 0.75486566, 0.59033514, 0.36507786])

In [12]:
# activation – default 'relu'
mlp_sigmoid = MLPClassifier(hidden_layer_sizes=(1000,), activation='logistic')
mlp_sigmoid.fit(X, Y)
cross_val_score(mlp_sigmoid, X, Y, cv=5)

array([0.63198861, 0.69982912, 0.76948638, 0.77356878, 0.4436954 ])

Combine what improved the model – multiple layers, higher alpha, and logistic activation function.

In [ ]:
mlp_2_layers_higher_alpha_sigmoid = MLPClassifier(hidden_layer_sizes=(1000,1000), alpha=0.001, activation='logistic')
mlp_2_layers_higher_alpha_sigmoid.fit(X, Y)
cross_val_score(mlp_2_layers_higher_alpha_sigmoid, X, Y, cv=5)